public class PokemonFactory {
    private static PokemonFactory pokemonFactory;

    private PokemonFactory() {
    }

    public static PokemonFactory getFactory() {
        if (pokemonFactory == null)
            pokemonFactory = new PokemonFactory();
        return pokemonFactory;
    }

    public Pokemon createPokemon(String nume) throws Exception {
        return switch (nume) {
            case "Neutrel1" -> new PokemonBuilder()
                    .cuNumele("Neutrel1")
                    .cuHP(10)
                    .cuNormalAttack(3)
                    .faraSpecialAttack()
                    .cuDefense(1)
                    .cuSpecialDefense(1)
                    .faraAbilitati()
                    .build();
            case "Neutrel2" -> new PokemonBuilder()
                    .cuNumele("Neutrel2")
                    .cuHP(20)
                    .cuNormalAttack(4)
                    .faraSpecialAttack()
                    .cuDefense(1)
                    .cuSpecialDefense(1)
                    .faraAbilitati()
                    .build();
            case "Pikachu" -> new PokemonBuilder()
                    .cuNumele("Pikachu")
                    .cuHP(35)
                    .faraNormalAttack()
                    .cuSpecialAttack(4)
                    .cuDefense(2)
                    .cuSpecialDefense(3)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(6)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(4)
                            .blocheazaAdversarul()
                            .seVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(5)
                            .build())
                    .build();
            case "Bulbasaur" -> new PokemonBuilder()
                    .cuNumele("Bulbasaur")
                    .cuHP(42)
                    .faraNormalAttack()
                    .cuSpecialAttack(5)
                    .cuDefense(3)
                    .cuSpecialDefense(1)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(6)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(5)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(3)
                            .build())
                    .build();
            case "Charmander" -> new PokemonBuilder()
                    .cuNumele("Charmander")
                    .cuHP(50)
                    .cuNormalAttack(4)
                    .faraSpecialAttack()
                    .cuDefense(3)
                    .cuSpecialDefense(2)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(4)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(7)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(6)
                            .build())
                    .build();
            case "Squirtle" -> new PokemonBuilder()
                    .cuNumele("Squirtle")
                    .cuHP(60)
                    .faraNormalAttack()
                    .cuSpecialAttack(3)
                    .cuDefense(5)
                    .cuSpecialDefense(5)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(4)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(3)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(2)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(2)
                            .build())
                    .build();
            case "Snorlax" -> new PokemonBuilder()
                    .cuNumele("Snorlax")
                    .cuHP(62)
                    .cuNormalAttack(3)
                    .faraSpecialAttack()
                    .cuDefense(6)
                    .cuSpecialDefense(4)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(4)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(5)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(0)
                            .nuBlocheazaAdversarul()
                            .seVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(5)
                            .build())
                    .build();
            case "Vulpix" -> new PokemonBuilder()
                    .cuNumele("Vulpix")
                    .cuHP(36)
                    .cuNormalAttack(5)
                    .faraSpecialAttack()
                    .cuDefense(2)
                    .cuSpecialDefense(4)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(8)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(6)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(2)
                            .nuBlocheazaAdversarul()
                            .seVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(7)
                            .build())
                    .build();
            case "Eevee" -> new PokemonBuilder()
                    .cuNumele("Eevee")
                    .cuHP(39)
                    .faraNormalAttack()
                    .cuSpecialAttack(4)
                    .cuDefense(3)
                    .cuSpecialDefense(3)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(5)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(3)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(3)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(3)
                            .build())
                    .build();
            case "Jigglypuff" -> new PokemonBuilder()
                    .cuNumele("Jigglypuff")
                    .cuHP(34)
                    .cuNormalAttack(4)
                    .faraSpecialAttack()
                    .cuDefense(2)
                    .cuSpecialDefense(3)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(4)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(3)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .build();
            case "Meowth" -> new PokemonBuilder()
                    .cuNumele("Meowth")
                    .cuHP(41)
                    .cuNormalAttack(3)
                    .faraSpecialAttack()
                    .cuDefense(4)
                    .cuSpecialDefense(2)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(5)
                            .nuBlocheazaAdversarul()
                            .seVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(1)
                            .nuBlocheazaAdversarul()
                            .seVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(3)
                            .build())
                    .build();
            case "Psyduck" -> new PokemonBuilder()
                    .cuNumele("Psyduck")
                    .cuHP(43)
                    .cuNormalAttack(3)
                    .faraSpecialAttack()
                    .cuDefense(3)
                    .cuSpecialDefense(3)
                    .cuAbilitatea1(new AbilityBuilder()
                            .cuDamage(2)
                            .nuBlocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(4)
                            .build())
                    .cuAbilitatea2(new AbilityBuilder()
                            .cuDamage(2)
                            .blocheazaAdversarul()
                            .nuSeVaFeriDeAbilitateaUrmatoare()
                            .cuCooldown(5)
                            .build())
                    .build();
            default -> new PokemonBuilder().build();

        };

    }
}
